### PR TITLE
colspan for table cells; cell-specific halign

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Added `colspan =>` option for a cell. This necessitated also adding `halign =>` option for a cell. `halign` is perhaps not the best name, but is consistent with the already existing `align =>`. Both `halign =>` and `align =>` take strings that can be used in `\begin{tabular}{<here>}` and `\multicolumn{}{<here>}{}`. These strings can have pipes, `>{commands}` for formatting contents, and of course `r`, `c`, `l`, `p{width}`, and `X`. The strings are used directly in TeX output. Whatever information can be extracted from them is converted to some CSS styling for HTML output. This introduces a lot of flexibility with cell-specific formatting that formerly was only available in HTML, not TeX.

Caught and fixed one small bug during testing where in TeX output, a cell that an author had marked as `TD` would nevertheless be formatted as `TH` if the whole row had been marked as a header row.

Also added some commentary. And moved a code block that gets used twice into a separate subroutine.

Test with below. This is the same .pg file I've used for testing before, but now two more DataTables are there to see `colspan` and `halign` for a cell.

```
DOCUMENT();      

loadMacros(
   "PGstandard.pl",
   "MathObjects.pl",     
   "niceTables.pl",
);

#########################################

TEXT(beginproblem());

$f = Formula("x^2");

#########################################

Context()->texStrings;
BEGIN_TEXT

An example with math objects and answer blanks.
$PAR

Fill in the table of values for \(f\) where \(f(x) = $f\).

\{DataTable([
["\(x\)", "\(0\)", "\(1\)", "\(2\)"],
["\(f(x)\)", ans_rule(5), ans_rule(5), ans_rule(5)],
],
align=>'cccc',
midrules=>1,
rowheaders=>1,
caption=>"\(f(x)=$f\)",
allcellcss=>'padding:6pt; ',
)\}

END_TEXT
Context()->normalStrings;

for my $i (0..2)
{ANS($f->eval(x=>$i)->cmp);};


BEGIN_TEXT
No frills.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
);
\}

Not centered.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
center=>0,
);
\}

Has a caption.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
);
\}

Midrules.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
);
\}

Left-aligned.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'lll',
);
\}

Left-center-right aligned.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'lcr',
);
\}

Fixed-width paragraph.
$PAR

\{
DataTable([
['I ','Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.'],
['II','A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.'],
], 
caption=>'Bill of Rights',
midrules=>1,
align=>'lp{2in}',
);
\}

Expandable-width paragraph.
$PAR

\{
DataTable([
['I ','Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.'],
['II','A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.'],
], 
caption=>'Bill of Rights',
midrules=>1,
align=>'lX',
);
\}

Vertical bars.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|l|c|r|',
);
\}

Text styles by column.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries} l |  >{\itshape} c  | >{\ttfamily} r  |  ',
);
\}

...with fore color.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries \color[HTML]{FF0000}} l |  >{\itshape} c  | >{\ttfamily\color{pink}} r  |  ',
);
\}

...and background color.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries \color[HTML]{FF0000}\columncolor{green}} l |  >{\columncolor[HTML]{33FF00}\itshape} c  | >{\ttfamily\color{pink}} r  |  ',
);
\}

Put everything in math mode.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
encase=>['\(','\)'],
);
\}

...with exceptions.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries',['ice cream',noencase=>1]],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
encase=>['\(','\)'],
);
\}

CSS applied to whole table.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
tablecss=>'border:solid 1px; ',
);
\}

CSS applied to caption.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
captioncss=>'text-decoration:line-through; ',
);
\}

CSS applied by column.
$PAR

\{
DataTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
columnscss=>['text-decoration:line-through; ','','text-decoration:overline; '],
);
\}

A header row.
$PAR

\{
DataTable([
[['apple ',headerrow=>1],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
);
\}

CSS header styling.
$PAR

\{
DataTable([
[['apple ',headerrow=>1],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
headercss => 'color:blue; ',
);
\}

CSS non-header styling.
$PAR

\{
DataTable([
[['apple ',headerrow=>1],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
datacss => 'color:blue; ',
);
\}

CSS for every cell.
$PAR

\{
DataTable([
[['apple ',headerrow=>1],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
allcellcss => 'font-family:fantasy; ',
);
\}

Row headers.
$PAR

\{
DataTable([
['apple','banana ','cherry'],
['durian','elderberrries','fig'],
['guava', ,'huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
rowheaders=>1,
);
\}

Row and column headers with a table header
$PAR

\{
DataTable([
[['apple',headerrow=>1,header=>'TH'],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava', ,'huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
rowheaders=>1,
);
\}

Row and column headers with no vertex header
$PAR

\{
DataTable([
[['apple',headerrow=>1,header=>'TD'],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava', ,'huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
rowheaders=>1,
);
\}

Individual cell manipulation.
$PAR

\{
DataTable([
[['apple', tex=>'\cellcolor[HTML]{FF0000}'],'banana ','cherry'],
['durian', ['elderberrries',tex=>'\color{green}'],['fig',m=>1]],
[['guava', b=>1],'huckleberries','ice cream'],
[['jackfruit', texencase=>['\emph{','}']],'kiwi',['lemon',cellcss=>'font-family:cursive; ']]], 
caption=>'Fruit',
);
\}

Row alteration.
$PAR

\{
DataTable([
[['apple', rowcolor=>'{yellow}'],'banana ','cherry'],
[['durian', rowcss=>'font-family:cursive; ',midrule=>1],'elderberrries','fig'],
['guava','huckleberries','ice cream'],
[['jackfruit', header=>'row'],'kiwi','lemon']], 
caption=>'Fruit',
);
\}

Alignment (and styling via tex alignment string) of a single cell
$PAR

\{
DataTable([
['apple','banana ','cherry'],
['durian','elderberrries','fig'],
['guava', 'huckleberries','ice cream'],
['jackfruit', ['kiwi', halign => '|>{\cellcolor{green}\bfseries}l'],'lemon']], 
caption=>'Fruit',
);
\}

Colspan 
$PAR

\{
DataTable([
[['applebananacherry',colspan=>"3", header=>"TH"]],
['durian','elderberrries','fig'],
['guava', ['huckleberries', colspan=>"2", halign=>'>{\color{blue}}r']],
['jackfruit', 'kiwi','lemon']], 
caption=>'Fruit',
);
\}

$HR
Layout tables
$PAR

No frills.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
);
\}

Not centered.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
center=>0,
);
\}

Midrules.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
);
\}

Left-aligned.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'lll',
);
\}

Left-center-right aligned.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'lcr',
);
\}

Fixed-width paragraph.
$PAR

\{
LayoutTable([
['I ','Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.'],
['II','A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.'],
], 
caption=>'Bill of Rights',
midrules=>1,
align=>'lp{2in}',
);
\}

Expandable-width paragraph.
$PAR

\{
LayoutTable([
['I ','Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.'],
['II','A well regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.'],
], 
caption=>'Bill of Rights',
midrules=>1,
align=>'lX',
);
\}

Vertical bars.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|l|c|r|',
);
\}

Text styles by column.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries} l |  >{\itshape} c  | >{\ttfamily} r  |  ',
);
\}

...with fore color.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries \color[HTML]{FF0000}} l |  >{\itshape} c  | >{\ttfamily\color{pink}} r  |  ',
);
\}

...and background color.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
midrules=>1,
align=>'|  >{\bfseries \color[HTML]{FF0000}\columncolor{green}} l |  >{\columncolor[HTML]{33FF00}\itshape} c  | >{\ttfamily\color{pink}} r  |  ',
);
\}

Put everything in math mode.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
encase=>['\(','\)'],
);
\}

...with exceptions.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries',['ice cream',noencase=>1]],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
encase=>['\(','\)'],
);
\}

CSS applied to whole table.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
tablecss=>'border:solid 1px; ',
);
\}

CSS applied by column.
$PAR

\{
LayoutTable([
['apple ','banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
columnscss=>['text-decoration:line-through; ','','text-decoration:overline; '],
);
\}

CSS for every cell.
$PAR

\{
LayoutTable([
[['apple ',headerrow=>1],'banana ','cherry'],
['durian','elderberrries','fig'],
['guava','huckleberries','ice cream'],
['jackfruit','kiwi','lemon']], 
caption=>'Fruit',
allcellcss => 'font-family:fantasy; ',
);
\}

Individual cell manipulation.
$PAR

\{
LayoutTable([
[['apple', tex=>'\cellcolor[HTML]{FF0000}'],'banana ','cherry'],
['durian', ['elderberrries',tex=>'\color{green}'],['fig',m=>1]],
[['guava', b=>1],'huckleberries','ice cream'],
[['jackfruit', texencase=>['\emph{','}']],'kiwi',['lemon',cellcss=>'font-family:cursive; ']]], 
caption=>'Fruit',
);
\}

Row alteration.
$PAR

\{
LayoutTable([
[['apple', rowcolor=>'{yellow}'],'banana ','cherry'],
[['durian', rowcss=>'font-family:cursive; ',midrule=>1],'elderberrries','fig'],
['guava','huckleberries','ice cream'],
[['jackfruit', header=>'row'],'kiwi','lemon']], 
caption=>'Fruit',
);
\}

END_TEXT



ENDDOCUMENT();        

```

### CODE REVIEW

**Comment by goehle** [comment]
Sorry its taken me a while to get to this. 

Is there a reason that the halign and colspan are only for DataTable?

**Comment by goehle** [comment]
Nevermind, I was misunderstanding what I was seeing.

**Comment by goehle** [comment]
Wait no, I had it right the first time.  The Layout tables don't seem to support colspan.

**Comment by Alex-Jordan** [comment]
Oops. I forgot that it all needs to be duplicated in the Layout block.
Thanks for catching that. I'll get to it soon I think.

On Thu, Aug 13, 2015 at 1:46 PM, Geoff Goehle <notifications@github.com>
wrote:

> Wait no, I had it right the first time. The Layout tables don't seem to
> support colspan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openwebwork/pg/pull/233#issuecomment-130836301>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
Apparently, display tables that are built using css display:table (like
niceTables' DisplayTable is) don't have a counterpart to colspan:

http://www.onenaught.com/posts/201/use-css-displaytable-for-layout#toc-some-limitations-or-issues

I'll have to think about this. First thoughts: still get the individual
cell alignment that is in this pull request into DisplayTable, and then
explicitly state no support for colspan in a display table.

On Thu, Aug 13, 2015 at 2:11 PM, Alex Jordan <alex.jordan@pcc.edu> wrote:

> Oops. I forgot that it all needs to be duplicated in the Layout block.
> Thanks for catching that. I'll get to it soon I think.
>
> On Thu, Aug 13, 2015 at 1:46 PM, Geoff Goehle <notifications@github.com>
> wrote:
>
>> Wait no, I had it right the first time. The Layout tables don't seem to
>> support colspan.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openwebwork/pg/pull/233#issuecomment-130836301>.
>>
>
>
>
> --
> Alex Jordan
> Mathematics Instructor
> Portland Community College
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
OK, I just explicitly stated in the documentation that colspan is not supported for LayoutTables. And I mentioned why it won't be.

The other stuff (cell-specific styling) was automatic for LayoutTables and works. You could just turn the one DataTable in the test file that uses `halign` in a cell into a LayoutTable and get a predictable result.

**Comment by goehle** [comment]
When I copied that DataTable to a LayoutTable the cell specific text
coloring wasn't working for me in hardcopy mode.  This was before your
latest changes so I'll double check that its still a thing.

**Comment by Alex-Jordan** [comment]
No need to check if you haven't already. It's still not there.

On Fri, Aug 14, 2015 at 4:14 AM, Geoff Goehle <notifications@github.com>
wrote:

> When I copied that DataTable to a LayoutTable the cell specific text
> coloring wasn't working for me in hardcopy mode. This was before your
> latest changes so I'll double check that its still a thing.
>
> On Fri, Aug 14, 2015 at 4:22 AM, Alex Jordan <notifications@github.com>
> wrote:
>
> > OK, I just explicitly stated in the documentation that colspan is not
> > supported for LayoutTables. And I mentioned why it won't be.
> >
> > The other stuff (cell-specific styling) was automatic for LayoutTables
> and
> > works. You could just turn the one DataTable in the test file that uses
> > halign in a cell into a LayoutTable and get a predictable result.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openwebwork/pg/pull/233#issuecomment-131017103>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openwebwork/pg/pull/233#issuecomment-131079763>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
halign now working for screen and hard copy, DataTable and LayoutTable.

colspan working for screen and hard copy, Datable only, with documentation that LayoutTable is not supported.

**Comment by goehle** [comment]
Colors and whatnot are working for LayoutTables now.  Everything works as advertised.

**Pull request merged**
