### PR TITLE
Fix erro in line 771 of PGmatrixmacros which made display_matrix() no…

### PR DESCRIPTION
**Pull request by mgage**
…t accept MathObjects.

Hot fix. This broke a lot of matrix problems when display_matrix() did not accept MathObject matrices.

### CODE REVIEW

**Comment by mgage** [comment]
Test using this:

## DESCRIPTION
Test using this:


```
DOCUMENT();   

loadMacros(
  "PG.pl",
  "PGbasicmacros.pl",
  "PGanswermacros.pl",
  "PGmatrixmacros.pl",
  "MathObjects.pl",
  "problemRandomize.pl"
);

TEXT(beginproblem());
$showPartialCorrectAnswers = 1;
ProblemRandomize(when=>"Correct",onlyAfterDue=>0);

$dim = 2;

Context ("Matrix");

$L = new Matrix($dim,$dim);
$U = new Matrix($dim,$dim);

foreach my $i (1..$dim) {
        foreach my $j (1..$dim) {
            if ($i<$j) {
                $L->assign($i,$j, 0);
             } else {
                $L->assign($i,$j, non_zero_random(-6,6,1));
             }
            if ($i>$j) {
                $U->assign($i,$j, 0);
             } else {
                $U->assign($i,$j, non_zero_random(-6,6,1));
             }
        }
}

#  We will want to solve LUx = b.  So, first pick x and work back out.
#  Let's start by picking a nice final solution for x.
$x = new Matrix($dim,1);
$xdisp = new Matrix($dim,1);

foreach my $i (1..$dim) {
   $x->assign($i,1, non_zero_random(-21,21,2)/2);
   $s = '\(x_'.$i.'\)';
   $xdisp->assign($i,1, $s);
}

#  Then create a mid-level solution for Ly = b so that Ux = y
$y = $U*$x;

#  Finally, we get the starting b = Ly that is displayed with L and U
$b = $L*$y;
Context()->texStrings;

BEGIN_TEXT
\{display_matrix($L)\}
END_TEXT


ENDDOCUMENT();

**Comment by drgrice1** [comment]
Shouldn't this be merged into master instead of PG-2.15 for a hot fix?

**Comment by mgage** [comment]
Ah right.

**Comment by gajennings** [comment]
It's perfect.  Thanks.  (I was planning to try to fix this by rewriting a zillion problems using math objects vectors but your solution is much better).

George
________________________________

**Pull request merged**
