### PR TITLE
fix bugs with answerHints from issue #964

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This fixes the issues discussed in #964.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks @dpvc. This now also addresses #872.

**Comment by Alex-Jordan** [comment]
Each issue has a MWE problem to test. For me, they both work following these changes.

**Comment by pstaabp** [comment]
This fixes #872, however I'm not seeing answer hints show up at all for the various MWEs.  Reading through #964 we need to implement the translation between the answer and the internal value like @dpvc pointed out, but that doesn't work for me either.

**Comment by Alex-Jordan** [comment]
Do I understand right that this can be merged, and #964 can remain closed, but #872 should be reopened but with extended comments? I think we ultimately want something where you do not have to insert that postFilter, and so #872's original MWE remains an issue although not quite for the same reasons. Or maybe #872 remains closed but I open a new issue.

**Comment by drgrice1** [comment]
This can be merged.  If you want to re-open #872 or create another issue regarding creating an easier way to make answer hints work with radio buttons or checkboxes, that would be good.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
