### PR TITLE
Scaffold opening reflows MathQuill answer boxes

### PR DESCRIPTION
**Pull request by drgrice1**
When a scaffold opens iterate through the MathQuill answer boxes on the
page and call reflow on each one so that the contents are properly
displayed.

See http://webwork.maa.org/moodle/mod/forum/discuss.php?d=4666

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Thanks for this. With apologies, I will be a bit slow on the review -- I'll aim for Friday.
Three classes tomorrow, all with tests, and only one of the three is ready for printing...

**Comment by sean-fitzpatrick** [comment]
Code looks fine to me. I haven't had a chance to test this. (Mid-semester and I don't have a testing server running.)

**Comment by drgrice1** [comment]
I would like to merge this in.

Mike:  Is this an appropriate change to merge into master?

**Comment by mgage** [comment]
I think this qualifies for hotfix status.  I think we can merge it.  Remember to merge an identical pull request into develop as well so that they will be in sync.

**Comment by Alex-Jordan** [comment]
This merged into `master`, but the parallel PR into `develop` #437 was deleted without being merged. I noticed this reviewing the diff between `master` and `develop` right now after I inadvertently merged #438 into `master` without its own parallel PR into develop.

**Comment by drgrice1** [comment]
Thanks for pointing that out. I will fix it tomorrow.

**Comment by drgrice1** [comment]
Alex, I am not sure what you are looking at, but this seems to have merged correctly. The changes are in the develop branch and in the master branch.

**Comment by Alex-Jordan** [comment]
OK, sorry, I'm misled by GitHub. In GitHub, pretend like you are going to open a PR from `openwebwork:master` into `openwebwork:develop`. GitHub shows that five commits would be part of that PR, with two files changed. Three of the commits are merge commits. The other two are 4d6aae4 (that brace removal) and 5e634d6 (the scaffold edit). It also shows the changes to the two files. But I guess it's not really a diff, but rather a compilation of what was in those commits.

It would be nice if when you are prepping a PR in GitHub, if GitHub showed the actual files diff between branches, not (just) a compilation of what is in the commits to be merged.

**Pull request merged**
