### PR TITLE
PG-2.15

### PR DESCRIPTION
**Pull request by mgage**
This is a version containing multilingual features  (utf8 4 byte characters). There are database changes so test cautiously  (backup up the database just in case).  If $ENABLE_UTF8MB4=0 you should  be able to use this on existing sites, even with mysql databases earlier  than 5.3.  If you set $ENABLE_UTF8MB4=1 then you will get a "wide  character" error message from the database if it is too old. If it is  new enough you will be able to use all characters including Chinese,  emoji, Arabic and so forth. (Download the companion WeBWorK-2.15-beta as  well.)

### CODE REVIEW

**Comment by mgage** [comment]
The only conflict in PG.pl is the version number.  I don't want to pull master into develop just to fix that.  We'll resolve it when we actually do the commit.

**Comment by taniwallach** [comment]
Note: The minor merge conflict is easy to handle.

**Comment by taniwallach** [comment]
Unless anyone has any additional urgent changes or objections - I think PG 2.15 is ready for release.
On the WW 2.15 side there are 3 "small" pending PRs:
  - https://github.com/openwebwork/webwork2/pull/1023
  - https://github.com/openwebwork/webwork2/pull/1025
  - https://github.com/openwebwork/webwork2/pull/1026

**Comment by drgrice1** [comment]
>     * [openwebwork/webwork2#1026](https://github.com/openwebwork/webwork2/pull/1026)

This pull request could certainly wait until 2.16.  There is no urgency for it to go into 2.15.

**Comment by taniwallach** [comment]
As far as I can tell there are no pending PRs or major issues for either pg or webwork2 remaining to hold off the release of 2.15.

The following "minor" issues may need to be addressed with hotfixes:
  - https://github.com/openwebwork/webwork2/issues/1028

**Pull request merged**
