### PR TITLE
Fixing Units.pm - value of electron volt

### LINKED ISSUE #677: Error in Units: electronVolt factor
The factor for `eV` is given as `1.60E-9` when [it should be](https://duckduckgo.com/?t=ffab&q=electron+volt+in+joules&ia=answer) `1.60E-19`

When this change is made, it would be a good opportunity to add in the larger units, `keV` and `MeV` for use in particle physics questions and perhaps `GeV` which gets used for very high energy gamma rays.

### PR DESCRIPTION
**Pull request by duffee**
This PR corrects the exponential for factor of eV in **lib/Units.pm**, which was out by a factor 10^10.
fixes #677

I've taken the opportunity to add definitions for `keV`, `MeV` and `GeV`.  These units are used in particle physics and for gamma ray energies.  The indentation in that section was tidied.

I've also added unit test files for Units.pm and updated the **t/README** with instructions and rationale.  I've found that the [Test2](https://metacpan.org/pod/Test2::V0) suite is a good framework for writing tests.  To make installing module dependencies easier, I've included a [cpanfile](https://metacpan.org/dist/Module-CPANfile/view/lib/cpanfile.pod) and instructions for different use cases.

### CODE REVIEW

**Comment by drgrice1** [comment]
Please either re-target this to the develop branch or the WeBWorK-2.17 release candidate branch.  We will not be adding hotfixes to the 2.16 release anymore.

**Comment by duffee** [comment]
In the Edit, did you mean that I should target the PG-2.17 branch, not the release candidate or target the PG-2.17 branch, not the develop branch?

**Comment by drgrice1** [comment]
Yes.  You should target the PG-2.17 branch.  That is the release candidate.  The main branch is the current release.  The develop branch is for future development that will not go into the upcoming release.

The release candidate PG-2.17 branch will be merged into both main and develop when the actual release occurs at the end of July.

**Comment by pstaabp** [comment]
Overall this looks good, but needs to be targeted on the other branch.

**Comment by pstaabp** [comment]
Overall this looks good, but needs to be targeted on the other branch.

**Review by drgrice1 — CHANGES_REQUESTED** [review]
I think that this will conflict with the unit tests that have already been added to the develop and release candidate branches.  It certainly will conflict with the README.md file.

I am not sure that I agree with the addition of the perl Test2::Suite module either.  I think it would be best to use the Test::More module already in use in the existing tests.  We don't need two different test suites.   There needs to be consistency in the way that the test files work as well.  The tests you are adding don't work the same as the existing tests.

I don't really think that the addition of the cpanfile is necessary.

**Comment by duffee** [comment]
I took the opportunity to add more tests and build up the test framework.  A new PR targeting PG-2.17 is in the pipeline.

Using a cpanfile is standard in software development these days for automating building and deployment stages.  It allows you to "pin" dependencies to specific versions in the case of known issues and it doesn't interfere with people whose workflows don't use it.

**Pull request closed without merging**
