### PR TITLE
Switch back to the reverted new method for the mq-editor toolbar focus.

### PR DESCRIPTION
**Pull request by drgrice1**
This is for testing for now.  Once Safari is updated we can put this back in.

### CODE REVIEW

**Comment by pstaabp** [comment]
This seems to be working again (Safari version 16.2)

**Comment by drgrice1** [comment]
Interesting.  Perhaps we should wait a bit to put this back, as users may need some time to update their browsers.

**Comment by taniwallach** [comment]
@Alex-Jordan Please test on your version of Mac OSX.

**Comment by drgrice1** [comment]
@Alex-Jordan: Could you test this on your older safari, and see if this works with that?

**Comment by Alex-Jordan** [comment]
I have this running and can test on Safari 14.1.2. But I'm not sure what I'm supposed to be testing.  Can you remind me?

**Comment by drgrice1** [comment]
Just test that the toolbar shows up and disappears correctly when a mathquill answer rule gains and loses focus.

**Comment by Alex-Jordan** [comment]
For the most part, it does.

If an input loses focus, and then quickly regains focus, the toolbar does
not stop its fadeout and goes away. But I think that is a separate issue.
This is with Safari 14.1.2.

On Tue, Apr 11, 2023 at 10:32 AM Glenn Rice ***@***.***>
wrote:

> Just test that the toolbar shows up and disappears correctly when a
> mathquill answer rule gains and loses focus.
>
> —
> Reply to this email directly, view it on GitHub
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-79541f0cbaf7e6aa&q=1&e=7970f6b0-b19b-4324-ae4d-fc7971337f98&u=https%3A%2F%2Fgithub.com%2Fopenwebwork%2Fpg%2Fpull%2F704%23issuecomment-1503818999>,
> or unsubscribe
> <https://protect2.fireeye.com/v1/url?k=31323334-501cfaeb-3132feb7-454455535732-1f5e7267f5030cf3&q=1&e=7970f6b0-b19b-4324-ae4d-fc7971337f98&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABEDOAC7IR6HGEHUW536JYTXAWISHANCNFSM55STGJGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by pstaabp** [comment]
The current version of Safari is 16.4 and this has been working in all of the 16.x versions.  There was a version 15 that wasn't working.   However, I think most versions of MacOS can install the latest Safari build (they are independent of OS version). 

Also, FYI: the beta version (aka Safari Technology Preview) has been working for quite a while now.

**Comment by drgrice1** [comment]
> For the most part, it does. If an input loses focus, and then quickly regains focus, the toolbar does not stop its fadeout and goes away. But I think that is a separate issue. This is with Safari 14.1.2.

That should be fixed now.  I added the part back that saves the toolbar to a local variable when removing it.  I thought that wasn't needed with this approach, but it is.  Thanks for pointing that out.

By the way, to reliably see this you can put focus at the beginning of a MathQuill answer input and quickly type "shift-tab" and then "tab".  Alternately when a MathQuill answer input has focus you can quickly click outside of the input, and then click in it again.  I can type faster than I can move the mouse though, so the first approach is more reliable for me.  For either of these, the toolbar should now come back properly now.

**Comment by Alex-Jordan** [comment]
So is this one ready to at least go back to "ready for review"?  If not all the way merged?

**Comment by drgrice1** [comment]
Yeah, I didn't realize I still had it on draft.

**Comment by Alex-Jordan** [comment]
I tested again, still working for me on Safari 14 (fwiw). And it works on Firefox. With the rest of you having tested and approved, I'll merge it now.

**Pull request merged**
