### PR TITLE
Update GeoGebra location for the deployggb.js file.

### PR DESCRIPTION
**Pull request by drgrice1**
The file is no longer available at the location in the code.  So GeoGebra problems are not working.

### CODE REVIEW

**Comment by drgrice1** [comment]
You can test this with Contrib/CUNY/CityTech/Calculus/setExplore_-_Graphing_the_Derivative/randomized-derivative-graph-with-solution.pg or Library/FortLewis/Calc1/06-01-Antiderivatives-graphically/AF2/AF2.pg, for example.  Of course there are many others in Contrib and the OPL.

**Comment by Alex-Jordan** [comment]
This raises the question for me: is there a good way to just directly enter `Library/FortLewis/Calc1/06-01-Antiderivatives-graphically/AF2/AF2.pg` somewhere and then I'm editing it? All I know of is workarounds where I put it in a set first then edit it, or navigate there with the Library Browser. Or I put it in a `render_rpc` URL that I have bookmarked.

**Comment by drgrice1** [comment]
I don't know if an easier way at this point.

**Review by Alex-Jordan — APPROVED** [review]
This works. I saw the broken problem before, and the fixed problem after.

**Review by pstaabp — APPROVED** [review]

**Pull request merged**
