### PR TITLE
PGML close math with any number of backtick or colon

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This addresses #654, but @dpvc should review this. I might be oversimplifying and introducing a new bug.

Also this does not address the PGML verbatim issue mentioned there.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
I'll note that this commit makes it work to have unbalanced math delimiters, like ````[`\pi``]````. The open delimiter determines which type of math it is.

But maybe we don't want that. Maybe it should be more like what @somiaj says in #654, that these situations should be recognized and there could be a better error message.

**Comment by somiaj** [comment]
If it is possible to detect and warn users if they aren't balanced, maybe do both, and issue a warning that only instructors can see, but render the problem.

**Comment by somiaj** [comment]
I just tested `````[`\pi````]````` (having four ticks when closing), it still closes, so I guess is working as it should, there are just extra "primes" shown, which I think is fine. I was almost going to suggest just changing the regex to ``qr/\`+\]/`` to allow for any number of closing ticks. But since it doesn't error out and visually someone can see the error probably not needed.

Basically #654 came out of spending way to long trying to figure out what was wrong with a long scaffold problem, when it was just due to not matching the number of ticks. I'm fine with this (provided there isn't unforeseen consequences) of allowing unmatching number of ticks, as this will help avoid a simple error that might otherwise be hard to find. The worst issue I could think of is something like ```[`\frac{\pi}{2}``]``` in which someone may have meant to open with two backticks, but had a typo. With this change, this would be easily seen when rendering the problem allowing them to fix it, and not error out.

**Comment by Alex-Jordan** [comment]
Closing this in favor of #980.

**Pull request closed without merging**
