### PR TITLE
Remove stray "}" from <script> url

### PR DESCRIPTION
**Pull request by Alex-Jordan**
This PR uses the same branch Andrew used to get 4d6aae4 into `master`. This branch also has two merge commits, and commit 5e634d6 that edits scaffold.pl. The content of 5e634d6 is already in develop, via commit d881134.

In addition to bringing 4d6aae4 into `develop`, this would clear up the network diagram a little, gathering all the commits that are officially in `master` right now but not in `develop`, and adding them.

Apologies if this is bad git practice, and we can close this PR and do something else. Trying to clean up the mess I made by merging #438 without checking the target branch.

### CODE REVIEW

**Comment by drgrice1** [comment]
The branch needs to be rebased on top of origin/develop.  Then it will merge cleanly.  If you merge it as it is it will add duplicates of the scaffold/mathquill commits that will appear in the git log.

**Comment by drgrice1** [comment]
This should be merged to keep the develop branch in line with the master branch.

I suggest the following procedure to do so cleanly without cluttering the git history.

From the command line do
`git checkout drdrew42-patch-1`
`git rebase origin/develop`
`git push --force`
Then from this page merge the pull request.

It may also be sufficient to just select "Rebase and merge" on this page, but I am not certain of what that will do.

**Comment by drgrice1** [comment]
Alex:  If you don't mind, I will take care of merging this for you.

**Comment by Alex-Jordan** [comment]
I don't mind :)  The term is wrapping up here and I'm traveling Sunday, so it's a slow time for me to get back to this. Thank you!

**Comment by taniwallach** [comment]
Glenn and Alex: Thanks for handling both these PRs.

**Pull request merged**
