### PR TITLE
Remove a prefix from the answer rule insertion of  parserGraphTool.pl

### PR DESCRIPTION
**Pull request by drgrice1**
This was from my original implemenation, and was not supposed to make it here.
The setNumber and probNum may not be defined, and in that case this fails.

### CODE REVIEW

**Comment by pstaabp** [comment]
This looks minor.  It doesn't appear that the id tag is ever used,  is that right?  If not, it doesn't really matter what it is named (as long as it is unique).

**Comment by drgrice1** [comment]
The id tag is used by the graphtool.js file.  That file is loaded by the macro and the method called on line 500 here with the id as the argument.  The file is located in the webwork2 code (in htdocs/js/apps/GraphTool).  That is the problem here.  If setNumber and probNum are undefined, then `$prefix = "not defined"`.  The space in that string doesn't work for an id.  The ANS_NAME should be unique without that.

**Comment by Alex-Jordan** [comment]
Tested and it didn't break a problem set. I also tried a problem in an undefined set, before and after, and I find no difference. I'm not sure how to trigger the `not defined` issue before the PR. But I'm just going to merge this anyway.

**Comment by drgrice1** [comment]
To trigger the "not defined" thing load a GraphTool problem via webwork2/html2xml

**Pull request merged**
