### PR TITLE
Update the scaffold html markup for bootstrap 5.

### PR DESCRIPTION
**Pull request by drgrice1**
This is paired with openwebwork/webwork2#1532 and will not work without that one.

### CODE REVIEW

**Comment by pstaabp** [comment]
@drgrice1 This looks nice too.  Looks like the accordion buttons are now bootstrap.  Anything else to look at for scaffolding?

**Comment by drgrice1** [comment]
That is pretty much it.  This pull request doesn't have that much too it.  PG doesn't directly use bootstrap that much.  I think there are a few other things that may be needed though.  I believe there are a few macros that use the `btn` class without one of the particular flavors (like `btn-primary`, `btn-secondary`, etc).  That doesn't work with bootstrap 5.

**Comment by drgrice1** [comment]
Actually, it seems that the only place that the `btn` class is directly used is in AppletObjects.pl, and I added the `btn-primary` class to that for WeBWorK-2.16.  So that is good.

**Review by pstaabp — APPROVED** [review]
Looks good.

**Pull request merged**
