### PR TITLE
IO Cleanup

### PR DESCRIPTION
**Pull request by goehle**
This is a bit of a cleanup of the PG IO system. 
-  It removes some methods `read_whole_file` and `createFile` that were not used.  
  -  Test by trying to use either method in a problem
-  It strips off any paths that might be part of `loadMacros`. 
  -  To test, add a path to something in `loadMacros` and check that only the file name is used.
-  Adds a check to read_whole_problem_file to see if problem file is coming from a courses directory. 
  -  To test, try and put `read_whole_problem_file('/webwork2/thing.pg')` in a problem 
-  Removes a couple of obsolete macro files from pg/macros.  

Note:   This needs to be tested with WeBWorK pull request 606.

### CODE REVIEW

**Comment by mgage** [comment]
This has some unexpected consequences when restricting file path.  We'll need to think about the right compromise:

Problem 6 in the Demo homework set (the CAPA problem) gives this error:

        Problem6
1. ERROR caught by Translator while processing problem file:setDemo/CAPA_example.pg
****************
ERRORS from evaluating PG file: 
 Error detected while loading [PG]/macros/PG_CAPAmacros.pl:
PG_macro_file_eval detected error at line 123 of file [PG]/lib/PGloadfiles.pm 
File path /Volumes/WW_test/opt/webwork/libraries/CAPA/CAPA_Tools/StdMacros.pg is unsafe. at [PG]/lib/WeBWorK/PG/IO.pm line 135,  chunk 1.
The calling package is PGloadfiles
   Died within PGloadfiles::compile_file called at line 168 of [PG]/lib/PGloadfiles.pm
   from within PGloadfiles::loadMacros called at line 457 of [PG]/macros/PG.pl
   from within main::loadMacros called at line 3 of (eval 3919)



****************

------Input Read
1		DOCUMENT(); 
2		
3		loadMacros( "PGbasicmacros.pl",
4			             "PGauxiliaryFunctions.pl",
5			             "PGchoicemacros.pl",
6			             "PGanswermacros.pl",
7			             "PGgraphmacros.pl",
8			             "PG_CAPAmacros.pl"
9		);

----------------------------------------------

and read_whole_problem_file("macros/PGcourse.pl");   fails to find "PGcourse.pl" -- probably because
the the macros/ segment is stripped.  I think this example should actually work -- otherwise you can only read a problem file that is in the top level of the course directory.

**Comment by mgage** [comment]
Here is a collection of uses of includePGproblem()   for redirecting problems in the OPL that needs to be respected. The redirects appear to work for the moment but this collection should continue to be checked.

Library/270/setDerivatives1/c1s5p9b.pg finds Library/maCalcDB/setDerivatives1/c1s5p9b.pg
at least from the Homework sets pages

OpenProblemLibrary/270/setDerivatives1/c1s5p8.pg:includePGproblem("Library/maCalcDB/setDerivatives1/c1s5p8.pg");
OpenProblemLibrary/270/setDerivatives1/c1s5p8b.pg:includePGproblem("Library/maCalcDB/setDerivatives1/c1s5p8b.pg");
OpenProblemLibrary/270/setDerivatives1/c1s5p9.pg:includePGproblem("Library/maCalcDB/setDerivatives1/c1s5p9.pg");
OpenProblemLibrary/270/setDerivatives1/c1s5p9b.pg:includePGproblem("Library/maCalcDB/setDerivatives1/c1s5p9b.pg");
OpenProblemLibrary/270/setDerivatives1/ns2_8_10.pg:includePGproblem("Library/Rochester/setDerivatives1/ns2_8_10.pg");
OpenProblemLibrary/270/setDerivatives1/ns2_8_31.pg:includePGproblem("Library/Rochester/setDerivatives1/ns2_8_31.pg");
OpenProblemLibrary/270/setDerivatives1/nsc2_1_5.pg:includePGproblem("Library/Rochester/setDerivatives1/nsc2_1_5.pg");

**Comment by mgage** [comment]
\{createFile('tmp/his','thing')\}   fails with the message unknown subroutine.  

Restricting creation of files directly from .pg problems seems prudent.  This subroutine in PG::IO is available to .pm files.

**Comment by mgage** [comment]
Just FYI  the changes to webwork2 (the File::Spec changes) -- don't cause any problems that I can find yet.

**Comment by goehle** [comment]
-  As long as the includePGproblem is using the Library symlink in the templates directory the read_whole_file changes shouldn't have any impact. 
-  Right now the capa path is hard coded to be `/opt/webwork/libraries/CAPA/`, which is not great anyway since the /opt/webwork is hardcoded.  I would recommend changing it to be `$courseDirs{templates}/Library/CAPA/CAPA_Tools/`.  Then if people want to use CAPA they should put the CAPA directory, or a symlink, into the OpenProblemLibrary folder.  This is similar to how it works if you want to use Contrib.  Alternatively I could just also allow reading from any file in /opt/webwork/libraries, or even any file in /opt/webwork.

**Comment by mgage** [comment]
At the moment Library is pointing to OpenProblemLibrary but CAPA, and 
some other useful problems are in Contrib which is at the same level as OpenProblemLibrary.

There is nothing in defaults.config
at the moment that points to webwork-open-problem-library/Contrib -- if there were 
we could use that as the prefix for the CAPA addresses.  

I believe one of the reasons
we put the paths to CAPA in default.config was because otherwise one had to create
several aliases in modelCourse in order to get to the CAPA graphics, the tools and the problems,
and describing the setup to newbies wanting to use CAPA problems was overly complicated.

**Comment by goehle** [comment]
Right.  That seems to be intentional.  There is all manner of stuff in Contrib.  So if you want to use it you add a link to Contrib inside OpenProblemLibrary.  Then you can access contrib via Libarary/Contrib.  I suggest something similar for CAPA.

**Comment by mgage** [comment]
OK.  That's reasonable site wide way to do it.  I have been adding
Contrib links to each course.

**Comment by jwj61** [comment]
You are right that there may be conflicts with OPL-update.  When Contrib was introduced, the idea was that it would get a link (by people who wanted it) as templates/Contrib, which seems to be the direction you are leaning now.

**Comment by goehle** [comment]
Mike and John are right.  I was misremembering.  The links should go in templates.  Thats a fine location for the CAPA link as well.

**Comment by mgage** [comment]
I've made the following changes in default.config in order to get CAPA to work properly with these changes.  Do you want to add these to your request Geoff? or should I pull your request and add the changes in a new pull request?

 ################################################################################
@@ -529,7 +529,7 @@ my $achievementTablesExist = (defined ($dbLayouts{$dbLayoutName}{global_user_ach
 #RE-CONFIGURE problemLibrary values in localOverrides.conf
 #################################################
 $problemLibrary{root}        ="/opt/webwork/libraries/webwork-open-problem-library/OpenProblemLibrary";
-$problemLibrary{version}     ="2.0"; # 2.0 for NPL, 2.5 for OPL
+$problemLibrary{version}     ="2.5"; # 2.0 for NPL, 2.5 for OPL
 ###########################################################

 # Problem Library SQL database connection information
@@ -1044,8 +1044,8 @@ $pg{specialPGEnvironmentVars}{use_javascript_for_live3d} = 1;

 # Locations of CAPA resources. (Only necessary if you need to use converted CAPA
 # problems.)
-$pg{specialPGEnvironmentVars}{CAPA_Tools}             = "/opt/webwork/libraries/CAPA/CAPA_Tools/",
-$pg{specialPGEnvironmentVars}{CAPA_MCTools}           = "/opt/webwork/libraries/CAPA/CAPA_MCTools/",
+$pg{specialPGEnvironmentVars}{CAPA_Tools}             = "$courseDirs{templates}/capaLibrary/macros/CAPA_Tools/",
+$pg{specialPGEnvironmentVars}{CAPA_MCTools}           = "$courseDirs{templates}/capaLibrary/macros/CAPA_MCTools/",
 $pg{specialPGEnvironmentVars}{CAPA_GraphicsDirectory} = "$webworkDirs{htdocs}/CAPA_Graphics/",
 $pg{specialPGEnvironmentVars}{CAPA_Graphics_URL}      = "$webworkURLs{htdocs}/CAPA_Graphics/",

**Comment by goehle** [comment]
I'll add them to this one.

**Comment by goehle** [comment]
Scratch that.  This is a pg pull.  Changes to default.config will have to go through webwork2.  If you make a pull request for that I will merge it.

**Comment by mgage** [comment]
Oops.  OK I’ll do that.
Take care,

Mike

**Pull request merged**
