### PR TITLE
Add support for q, qq, and qr string quoting operator within [@...@] PGML blocks (#759)

### PR DESCRIPTION
**Pull request by dpvc**
This PR provides for proper handling of `q!...!`, `qq!...!` and `qr!...!` strings in `[@ ... @]` blocks in PGML.  This fixes the problem reported in #759 by @Alex-Jordan, and his examples can be used as test cases.

The quoted strings are handled by a new `Quoted()` method that modifies the token list (`$self->{split}`) directly by hand (rather than going through the usual token processing loop) since the `q` delimiter charter is not known when the PGML string is initially split into tokens.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
Thanks Davide, this is great and will address the issue that started this (which has to do with PreTeXt's automated translation of PTX to PG.) I was thinking about how those perl `q` operators work, and there are at least five differences with how this would behave.

1. The `.` at line 46 is not supposed to be a word character or white space.
2. Or, if the `q` (`qq`, `qr`) is immediately followed by white space, then the next character is the delimiter, and now it may be a word character.
3. If the delimiter is among `([{` then the closer is supposed to be the corresponding character from `)]}`. (I checked and something like `q[foo[` does not work.)
4. Nesting of regular delimiters is still respected. For example `q{{foo}}` makes "{foo}".
5. The would-be terminating character may be escaped. This is even true with regular quoting like `"fo\"o"`. While this is supposed to be true for perl in general, it seems that in PG, the Translator is already having trouble with something like that example.

1 through 3 seem like they can be addressed with small changes to this PR. I'll give it a try. I thought I'd check with you first to see if anything I wrote here sounds wrong.

4 seems hard. It doesn't impact the PTX use case though, where `q` will be used with some non-delimiter character. I only mention it to see if some magic occurs to you.

5 seems moot if Translator is already not handling that the way base perl would handle it.

**Comment by dpvc** [comment]
Alex, after I made the PR yesterday, I was thinking about it further, and already had realized I needed to avoid white space for the delimiter, but I appreciate the fuller details about the possibilities.  I also wonder about whether there should be some restriction on what comes before the `q` as well, like a word break.

You are right that 1 through 3 should be straight-forward.  4 is not that hard, and I have written delimiter-balancing code many times, so that should not be a problem.  The `Quote()` method just needs to take that into account.  I'll work something up for that.

For 5, that is due to PG's doubling of all backslashes.  The `PGML::Format()` removes the doubles, so I believe that inside `BEGIN_PGML/END_PGML`, you should be able to do things like `[@ "fo\"o" @]`, but the `PGML()` function calls `PGML::Format2()` which first doubles all backslashes like PG does and then calls `PGML::Format()` on the result.  That was designed so that you can use `PGML()` in macro files that aren't processed with PG's backslash doubling.  But if you use `PGML()` in a PG file directly, it will end up getting quadrupled backslashes instead.  So you would want to use `PGML::Format()` directly if you need this within `.pg` files rather than `.pl` files, or use something like `PGML('[@ "fo~~"o" @])`, since the `~~` will ben turned into a single backslash before the PGML command is executed.  I understand the need for the backslash doubling, but it sure does cause problems at times.

So I think the backslash stuff for 5 does need to be handled.  It already is for single and double quotes, but not for `q` or the others.

**Comment by dpvc** [comment]
I've pushed an update that should take care of your five issues.  See if that works better.

**Comment by pstaabp** [comment]
On testing the first MWE of @Alex-Jordan of #759, I'm getting the following errors:
```
Use of uninitialized value $code in concatenation (.) or string at [PG]/lib/WeBWorK/PG/Translator.pm line 1351
from within PGML::Eval called at line 895 of [PG]/macros/core/PGML.pl
from within PGML::Parse::replaceCommand called at line 1327 of [PG]/macros/core/PGML.pl
from within PGML::Format::Command called at line 1192 of [PG]/macros/core/PGML.pl
from within PGML::Format::string called at line 1371 of [PG]/macros/core/PGML.pl
from within PGML::Format::html::Indent called at line 1185 of [PG]/macros/core/PGML.pl
from within PGML::Format::string called at line 1172 of [PG]/macros/core/PGML.pl
from within PGML::Format::format called at line 1816 of [PG]/macros/core/PGML.pl
from within PGML::Format called at line 1826 of [PG]/macros/core/PGML.pl
from within PGML::Format2 called at line 15 of tmpEdit/setGitHub_759/test1.pg.peter.tmp
```

and this is the same error I see on develop.  I doubled checked that I have the new code.  There's a Quoted method that is being called.

**Comment by drgrice1** [comment]
I am seeing the same warnings that @pstaabp saw.  Specifically for
```perl
BEGIN_PGML
[@ PGML(q!It's not here.!) @]*
END_PGML
```
and
```perl
BEGIN_PGML
[@ q!it's a string! @]
END_PGML
```
from @Alex-Jordan's examples.

**Comment by dpvc** [comment]
I've pushed another commit that should resolve the issues @pstaabp and @drgrice1 are seeing.  Sorry about that; they were due to a last minute change, and I also fixed another issue that I found while testing those problems.

**Comment by drgrice1** [comment]
Your latest commit fixed the errors with @Alex-Jordan's examples.  However, this pull request is causing an issue with variable substitution in PGML as in the following example:
```
$a = 5;
BEGIN_PGML
[`[$a]`]
END_PGML
```

**Comment by drgrice1** [comment]
Actually, you just need `[$a]` and not the PGML math mode delimiters.

**Comment by pstaabp** [comment]
@drgrice1 I'm not seeing a problem with the variable substitution.  It looks like this seem to fix the issues above.  Here's the file I just ran:
```
DOCUMENT();
loadMacros("PGstandard.pl","PGML.pl");

$a = 5;

BEGIN_PGML
[$a] [`[$a]`]
END_PGML

ENDDOCUMENT();
```

**Comment by drgrice1** [comment]
So the issue is specific to the letter "q".

**Comment by drgrice1** [comment]
Use
```
$q = 5;

BEGIN_PGML
[$q]
END_PGML
```
to see the issue.

**Comment by dpvc** [comment]
> So the issue is specific to the letter "q".

Yes, I see why.  I was afraid there might be a situation like that, but didn't think of this one.  I will think about how to address it.  It might be enough to disallow `]` and `@` as `q` delimiters, but probably better to not make the delimiter part of the pattern.

**Comment by dpvc** [comment]
OK, I've made changes that should allow handling of `[$q]` and also things like `[@ $q @]` that would have failed as well.

**Comment by dpvc** [comment]
OK, I see the failed unit test and will make another commit, but am out of time right now.

**Comment by dpvc** [comment]
OK, made the changes.

**Comment by drgrice1** [comment]
Your latest changes do fix the `$q` issue!  Thanks.

**Comment by dpvc** [comment]
I've modified the regex used for the q-strings to make it work better in some edge cases (in particular, if the `q` directory follows `[@` with no space).  This should also be more efficient, since it avoids the lookbehind regex.

**Review by pstaabp — APPROVED** [review]
This looks good now.

**Review by drgrice1 — APPROVED** [review]
This looks pretty good now.  Thanks for fixing the issues, and working on this to begin with.

**Comment by dpvc** [comment]
It took a bit to get it right, but glad that this seems to do the trick.

**Pull request merged**
