### PR TITLE
add maketext calls in lib/Value/Interval.pm

### PR DESCRIPTION
**Pull request by heiderich**
This uses the subroutine Value::maketext() added by @mgage in #298

### CODE REVIEW

**Comment by mgage** [comment]
Need to wait until the Value::maketext() function is defined before pulling this request.

**Comment by dpvc** [comment]
This is the wrong way to accomplish this.  All the error messages go through one place, the `Value::Error` routine, so that is the better place to put these calls.  Note that if you use `maketext()`  at this location, you will disable the MathObjects facility for translating error messages to other phrases, which is used multiple problems to change the error messages to something more appropriate.  Also, you would have to add `maketext()` to every macro file that produces a message, and many of the error messages use the MathObject substitution mechanism (`sprint`-like) to insert parameters into the messages (this is intimately tied to the messages transformation system).  So I would not recommend using `maketext()` in this way, but incorporate it into the `Value::Error` function, and perhaps one or two others.

**Comment by heiderich** [comment]
You propose to incorporate maketext() in Value::Error. Since this would make maketext() calls in the macro files obsolete, it appears to make localization even easier.

You say that problems can modify the error messages. Can you point me to an example? How should this be handled in terms of localization? When I understand it correctly, the error messages will not be predictable. Are the standard error messages modified (for instance using regular expressions) or are completely new error messages provided by the problems? If the latter is the case, these could easily be translated when a problem is translated into another language. In the former case I guess it would be more difficult, since no corresponding entries may exist in the .po file.

**Comment by mgage** [comment]
As I understand it (and I may not understand it properly)  maketext(...)  has two functions. (1) Is to translate the enclosed text fed to the maketext function.  (2) Is to flag the enclosed text so that gettext() can extract the phrase from the code and place it into a .po file for translation.  If we put the translation function into Value::Error(), which seems preferable, we will have to figure out an alternative method for accomplishing function (2).

**Comment by dpvc** [comment]
> we will have to figure out an alternative method for accomplishing function (2).

Most of the strings in question will be in calls to `Value::Error()` or `Value->Error()`, or a couple of other calls (I will need to make a list).  You could modify `gettext` to look for these as well when creating the `.po` file (or make separate program to look for them if you don't want to modify `gettext`).

**Comment by dpvc** [comment]
> Can you point me to an example?

A quick search of the OPL find the following problems use the MathObject message transformation facilities.  I haven't looked more closely to see what they actually do.

```
AlfredUniv/diffeq/annihilators/diffoperator6.pg
AlfredUniv/diffeq/annihilators/solve1.pg
AlfredUniv/diffeq/annihilators/solve2.pg
AlfredUniv/diffeq/annihilators/solve3.pg
AlfredUniv/diffeq/annihilators/solve4.pg
AlfredUniv/diffeq/constantcoefficient/constant2.pg
AlfredUniv/diffeq/constantcoefficient/constant3.pg
AlfredUniv/diffeq/Fourier/computecoefficients1.pg
AlfredUniv/diffeq/Fourier/halfinterval/halfrangeexpansion2.pg
AlfredUniv/diffeq/Fourier/halfinterval/halfrangeexpansion3.pg
AlfredUniv/diffeq/linear/duiller.pg
AlfredUniv/diffeq/linear/prob8.pg
AlfredUniv/diffeq/linear/prob9.pg
AlfredUniv/diffeq/modeling/torricelli.pg
AlfredUniv/diffeq/ReductionOfOrder/LRC.pg
AlfredUniv/diffeq/ReductionOfOrder/multiplicitytwo.pg
AlfredUniv/diffeq/sturmlouiville/findlambda1.pg
AlfredUniv/diffeq/sturmlouiville/findlambda2.pg
AlfredUniv/diffeq/sturmlouiville/findlambda3.pg
AlfredUniv/PDE/othercoordinates/laplacianderive.pg
AlfredUniv/PDE/othercoordinates/vibratingdrumhead.pg
AlfredUniv/PDE/separable/heat/constantends1.pg
AlfredUniv/PDE/separable/heat/insulatedends1.pg
AlfredUniv/PDE/separable/higherdimensional/twodimensionalwave.pg
AlfredUniv/PDE/separable/laplace/dirichlet.pg
AlfredUniv/PDE/separable/nonhomogeneous1.pg
AlfredUniv/PDE/separable/nonhomogeneous3.pg
AlfredUniv/PDE/separable/separate2.pg
AlfredUniv/PDE/separable/wave/zeropartial.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait10.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait11.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait12.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait13.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait14.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait15.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait16a.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait17.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait18.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait19.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait2.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait20.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait3.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait4.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait5.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait6.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait7.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait8.pg
CSUOhio/differential_equations/phasePortrait/phasePortrait9.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_03_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_04_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_13_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_16_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_17_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_18_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_19AnswerHelp_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_20_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_21_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_23_Factor.pg
CollegeOfIdaho/setAlgebra_05_06_Factoring/56IntAlg_29_Factor.pg
CollegeOfIdaho/setStatistics_Ch10Probability/10Stats_10_Probability.pg
CollegeOfIdaho/setStatistics_Ch10Probability/10Stats_11_Probability.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-04-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-06-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-08-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-12-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-16-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-20-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-24-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-52-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-56-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-60-Algebraic-fractions.pg
FortLewis/Algebra/2-4-Algebraic-fractions/MCH1-2-4-64-Algebraic-fractions.pg
FortLewis/Algebra/3-2-Solving-inequalities/MCH1-3-2-06-Solving-inequalities.pg
FortLewis/Algebra/7-3-Power-equations/MCH1-7-3-04-Power-equations.pg
FortLewis/Authoring/Templates/Algebra/AlgebraicFractionAnswer1.pg
FortLewis/Authoring/Templates/Algebra/AlgebraicFractionAnswer1_PGML.pg
FortLewis/Authoring/Templates/Algebra/EquationImplicitFunction1.pg
FortLewis/Authoring/Templates/Algebra/EquationImplicitFunction1_PGML.pg
FortLewis/Calc3/17-1-Parametrized-curves/HGM4-17-1-16aa-Parametrized-curves.pg
FortLewis/Calc3/17-1-Parametrized-curves/HGM4-17-1-16b-Parametrized-curves.pg
FortLewis/Calc3/17-1-Parametrized-curves/HGM4-17-1-16bb-Parametrized-curves.pg
FortLewis/Calc3/17-1-Parametrized-curves/HGM4-17-1-16d-Parametrized-curves.pg
FortLewis/Calc3/17-1-Parametrized-curves/HGM4-17-1-16f-Parametrized-curves.pg
Hope/Multi1/04-02-Kernel-image/Ker_im_06.pg
Hope/Multi2/09-02-Parametric-curves/Parametric-curves-3D-01/Parametric-curves-3D-01.pg
Hope/Multi2/09-02-Parametric-curves/Parametric-curves-3D-02.pg
Hope/Multi2/09-02-Parametric-curves/Parametric-curves-3D-03.pg
Indiana/Indiana_setSeries9Taylor/e8_7_3new.pg
LoyolaChicago/Precalc/Chap5Tools/Connally3-5-Tools-15.pg
LoyolaChicago/Precalc/Chap6Sec4/Q04.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-07.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-11.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-12.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-14.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-18.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-19.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-20.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-22.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-28.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-35.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-36.pg
LoyolaChicago/Precalc/Chap9Tools/Connally3-9-Tools-37.pg
METU-NCC/Diff_Eq/pde-heat1.pg
METU-NCC/Diff_Eq/pde-heat2.pg
METU-NCC/Diff_Eq/pde-heat3.pg
Michigan/Chap12Sec1/Q11.pg
Michigan/Chap12Sec1/Q31.pg
Michigan/Chap12Sec3/Q14.pg
Mizzou/Algebra/exponents_integers/exp_ints_25.pg
Mizzou/Algebra/graph_polynomials/find_all_info_01.pg
Mizzou/Algebra/inequalities_linear/linear_13_ia_npl.pg
Mizzou/Algebra/log_eqns_convert_to_and_from_exp/log_to_exp_03.pg
Mizzou/Algebra/rational_expressions_canceling/cancel_01.pg
Mizzou/Algebra/rational_expressions_canceling/cancel_02.pg
Mizzou/Algebra/rational_expressions_canceling/cancel_03.pg
Mizzou/Algebra/rational_expressions_mult_div/multiply_01.pg
Mizzou/College_Algebra/Equations_Linear/Var4.pg
Mizzou/College_Algebra/Equations_Linear/Var5.pg
Mizzou/College_Algebra/Equations_Linear/Var6.pg
Mizzou/College_Algebra/Equations_Linear/Variables2.pg
Mizzou/College_Algebra/Equations_Linear/Variables3.pg
Mizzou/College_Algebra/Real_Numbers/Absolute_Value/Find_Distance_Between_Integer_Numbers.pg
Mizzou/College_Algebra/Real_Numbers/Absolute_Value/Find_Distance_Between_Rational_Numbers.pg
Mizzou/College_Algebra/Real_Numbers/Absolute_Value/Simplify_Absolute_Value.pg
Mizzou/College_Algebra/Real_Numbers/Order_of_Operations/Two_Parts_02.pg
Mizzou/College_Algebra/Real_Numbers/Simplifying_Expressions/Simplifying_Algebraic_Expressions_02.pg
Mizzou/College_Algebra/Real_Numbers/Simplifying_Expressions/Simplifying_Algebraic_Expressions_03.pg
Mizzou/Intermediate_Algebra/Exponent_Laws/No_Var_Denom.pg
Mizzou/Intermediate_Algebra/Exponent_Laws/One_Var_Const_Dont_Cancel.pg
Mizzou/Intermediate_Algebra/NPL_Files/Inequalities/41IntAlg_22_LinearIneq.pg
PCC/BasicAlgebra/AlgebraicProperties/SimplifyInContext10.pg
PCC/BasicAlgebra/Exponents/exponentDivision0.pg
PCC/BasicAlgebra/Exponents/exponentDivision10.pg
PCC/BasicAlgebra/Exponents/exponentDivision100.pg
PCC/BasicAlgebra/Exponents/exponentDivision105.pg
PCC/BasicAlgebra/Exponents/exponentDivision15.pg
PCC/BasicAlgebra/Exponents/exponentDivision25.pg
PCC/BasicAlgebra/Exponents/exponentDivision5.pg
PCC/BasicAlgebra/Exponents/exponentDivision60.pg
PCC/BasicAlgebra/Exponents/exponentDivision65.pg
PCC/BasicAlgebra/Exponents/exponentDivision70.pg
PCC/BasicAlgebra/Exponents/exponentDivision75.pg
PCC/BasicAlgebra/Exponents/exponentDivision90.pg
PCC/BasicAlgebra/Exponents/exponentDivision95.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication0.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication15.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication20.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication23.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication24.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication25.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication30.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication35.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication40.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication45.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication5.pg
PCC/BasicAlgebra/Exponents/exponentsMultiplication50.pg
PCC/BasicAlgebra/Factoring/factoring200.pg
PCC/BasicAlgebra/Factoring/factoring355.pg
PCC/BasicAlgebra/FractionArithmetic/AddingFractionsOfInches10.pg
PCC/BasicAlgebra/GraphingQuadratics/IdentifyAxisVertex100.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator100.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator130.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator40.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator45.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator50.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator60.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator70.pg
PCC/BasicAlgebra/RadicalsAndRationalExponents/RationalizeDenominator80.pg
PCC/BasicAlgebra/SystemsOfLinearEquations/systemsOfEquations70.pg
PCC/BasicAlgebra/SystemsOfLinearEquations/systemsOfEquations80.pg
```

Also the following macro files in the OPL:

```
macros/PCC/contextInequalitySetBuilder.pl
macros/PCC/contextRationalExponent.pl
macros/PCC/SolveLinearEquationPCC.pl
```

And the following in `pg/macros`:

```
contextCurrency.pl
contextFraction.pl
contextInequalitySetBuilder.pl
contextOrdering.pl
contextPermutation.pl
contextScientificNotation.pl
```

As for how to handle them, I assume that the problems would be handled as you suggest (during translation).  For the macro files, the strings could be added to the .po files directly.  Some of the messages include `sprintf`-style substitutions of other strings (mostly things like object class names like "Number" or "Function returning a number").  Getting those things translated will be more of a challenge.  Also, there are places where plurals are handled by adding "s", and that won't be appropriate for other languages.  So there are more substantial changes needed to the internals of MathObjects to really make this all feasible.

**Comment by mgage** [comment]
I think that will work. I just wanted to document the need to handle the collection of phrases.  I'd like to see a procedure set down for periodically scraping the code base, finding new strings and updating the translating files.  

I don't know the best way to do this.  There may be some suggestions on https://www.transifex.com/
about the best way to do this.  It's been a long time since we started the localization project and there have been improvements in the tools available. WeBWorK has an account at www.transifex.com where we store our .po files in a public place.

**Comment by dpvc** [comment]
I have looked through he code and there seem to be only about 4 functions that would need attention.

The main one is [Context->setError()](https://github.com/openwebwork/pg/blob/master/lib/Value/Context.pm#L136-L152), where you might want to call `maketext()` in more than one place.  It depends on whether you want to translate the message before substitutions or after (or both).  If before, then you would want to call `maketext()` for the original `$message` as well as `$more` and all the entries in `@args`.  If after, then perhaps trying to translate after line 141, after line 145, and after line 147.

The `setError()` call should handle most things (in particular, `Value::Error()` calls it, so that would handle the main error messages).

There is also [Value->cmp_Error()](https://github.com/openwebwork/pg/blob/master/lib/Value/AnswerChecker.pm#L304-L309), [Value->entryMessage()](https://github.com/openwebwork/pg/blob/master/lib/Value/AnswerChecker.pm#L304-L309), and 
[MultiAnswer->setMessage()](https://github.com/openwebwork/pg/blob/master/macros/parserMultiAnswer.pl#L405-L408).  The first and last of these are straight forward (just translate `$message`), but for `entryMessage()`, you might need to translate the `"In entry"` string as well.

I think that would get you pretty far along, if not everything.

**Comment by heiderich** [comment]
>  For the macro files, the strings could be added to the .po files directly. Some of the messages include sprintf-style substitutions of other strings (mostly things like object class names like "Number" or "Function returning a number"). Getting those things translated will be more of a challenge. Also, there are places where plurals are handled by adding "s", and that won't be appropriate for other languages. So there are more substantial changes needed to the internals of MathObjects to really make this all feasible.

I think it could be helpful to compile a list of places that are affected in order to understand what kind of problems need to be addressed concretely. Then we may try to come up with a solution that handles them properly. Unfortunately I am not sufficiently familiar with the internals of MathObjects. So I would appreciate your help.

**Comment by heiderich** [comment]
> I'd like to see a procedure set down for periodically scraping the code base, finding new strings and updating the translating files.

I think webwork comes with a script that (re)generates the `webwork.pot` file and there are tools that can merge a pot file with a po file.

So I think this procedure may be automated as follows: Use git hooks to trigger a script that for each new commit in the master/develop branches does roughly the following:

1) check out the current master/develop branch
2) generate the pot file
3) merge the pot file with each po file in webwork2/lib/WeBWorK/Localize/
4) commit the pot file and the po files
5) create a pull request to the master/develop branch (if github has an API that allows this)

**Pull request merged**
